name: desktop_security_center
description: Desktop Security Center
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_svg: ^2.0.9
  handy_window: ^0.3.1
  provider: ^6.0.5
  ubuntu_logger: ^0.1.0
  ubuntu_service: ^0.3.0
  ubuntu_test: ^0.1.0-beta.4
  upower: ^0.7.0
  url_launcher: ^6.2.4
  yaml: ^3.1.2
  yaru: ^1.1.0
  yaru_colors: ^0.1.7
  yaru_icons: ^2.2.2
  yaru_widgets: ^3.2.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.3.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svgs/
