name: prompting_client_ui
description: 'A Flutter UI for apparmor prompting.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.2'

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.3
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  measure_size: ^4.0.0
  measure_size_builder: ^1.0.3
  prompting_client: ^1.0.0
  riverpod_annotation: ^2.3.5
  ubuntu_lints: ^0.4.0
  ubuntu_localizations: ^0.4.0
  ubuntu_logger: ^0.1.1
  ubuntu_service: ^0.3.2
  url_launcher: ^6.3.0
  window_manager: ^0.3.9
  yaru: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  yaru_test: ^0.1.6

flutter:
  uses-material-design: true
  generate: true
