name: security_center
description: "Desktop Security Center"
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  args: ^2.5.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  path: ^1.9.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  snapd: ^0.6.2
  ubuntu_localizations: ^0.3.0
  ubuntu_logger: ^0.1.1
  ubuntu_service: ^0.3.2
  xdg_directories: ^1.0.4
  yaru: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  ubuntu_lints: ^0.4.0

flutter:
  uses-material-design: true
  generate: true
