name: security_center
description: "Desktop Security Center"
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  args: ^2.5.0
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  snapd:
    git:
      url: https://github.com/d-loose/snapd.dart
      ref: prompting-rules
  ubuntu_logger: ^0.1.1
  ubuntu_service: ^0.3.2
  yaru: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  ubuntu_lints: ^0.4.0

flutter:
  uses-material-design: true
  generate: true
