name: security_center
description: "Desktop Security Center"
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  args: ^2.5.0
  barcode_widget: ^2.0.4
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  file: ^7.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.3
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3
  flutter_riverpod: ^2.5.1
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.4.1
  handy_window: ^0.4.0
  path: ^1.9.0
  riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  snapd: ^0.7.0
  ubuntu_localizations: ^0.5.2+1
  ubuntu_logger: ^0.2.0
  ubuntu_service: ^0.4.0
  url_launcher: ^6.3.0
  xdg_desktop_portal: ^0.1.13
  xdg_directories: ^1.0.4
  yaru: ^7.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter

  freezed: ^2.5.2
  integration_test:
    sdk: flutter
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  ubuntu_lints: ^0.4.1

flutter:
  uses-material-design: true
