name: aa_prompt_ui
description: "A Flutter UI for apparmor promptingf."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  yaru:
    git:
      url: https://github.com/ubuntu/yaru.dart.git
      ref: main
  yaru_widgets: ^1.1.2
  ubuntu_lints: ^0.3.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
