name: apparmor_prompting_client
description: Dart client for the AppArmor prompting gRPC service.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  freezed_annotation: ^2.4.4
  grpc: ^3.2.4
  json_annotation: ^4.9.0
  protobuf: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  test: ^1.24.0
  ubuntu_lints: ^0.4.0
